# Generated by Django 3.2.4 on 2021-06-20 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('about_me', models.TextField()),
                ('job_title', models.CharField(max_length=100)),
                ('title_description', models.TextField()),
                ('age', models.IntegerField()),
                ('degree', models.CharField(max_length=100)),
                ('instituion', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('home_address', models.CharField(max_length=200)),
                ('blood_group', models.CharField(choices=[('O', 'O+'), ('A', 'A+'), ('B', 'B+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB')], max_length=100)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
