# Generated by Django 3.2.4 on 2021-06-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='career_summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='company',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='freelancer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pass_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='services',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills',
            field=models.CharField(default='', max_length=100),
        ),
    ]
